name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Ubuntu Version
        run: cat /etc/issue

      - name: Checkout
        uses: actions/checkout@v3.0.1

      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '1.15'
          check-latest: false

      - name: Go Version
        run: go version

      - name: Go Build
        run: GOOS=linux GOARCH=amd64 go build -o ci.bin main.go

      - name: Run
        run: ./ci.bin


